### ISSUE TITLE
Would you be open to rescuing the bionics mods?

### ISSUE THREAD

**Issue by sunlightspectre** [emipa606/PlayableKobolds#1]
RBSE, especially; but anything, really. Playable species get hit hard if they can't replace their various limbs, after all.
It's not priority, I already appreciate your efforts to revive 'forgotten' mods enough.
Thanks!

**Comment by emipa606** [comment]
I might have time to look at it. It would help a lot if you could link to them on the Discord server https://invite.gg/Mlie
That way it can be easily added to my todo-list if possible :)
